GET http://localhost:3000/

###

POST http://localhost:3000/routes/add
Content-Type: application/json      

{
    "account_id": "44444444",
    "limit": "3434465"
}

###

POST http://localhost:3000/add
Content-Type: application/json      

{
    "value": 50
}

###

PUT http://localhost:3000/up
Content-Type: application/json      

{
    "_id": "6347499c4d49f82493f14604",
    "newVal": 5677464767
}


//empty line above Content-Type is critical